name: 'github-action-publish-binaries'
description: 'Post files to an http server'
author: 'Patrick Aljord'
branding:
  icon: save
  color: black
inputs:
  args:
    description: 'The pattern of files to upload'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.args }}
