#!/bin/bash
#
# Upload binary artifacts when a new release is made.
#
# We should be invoked with a pattern for files to upload,
# and optionally the release-ID to associate them with.
#
# These will be stored in the environment as:
#
#   INPUT_ARGS
#
#   INPUT_RELEASEID
#
#

#
# Ensure that the GITHUB_TOKEN secret is included
#
if [[ -z "$POST_URL" ]]; then
  echo "Set the post URL env variable."
  exit 1
fi

#
# Ensure that there is a pattern specified.
#
if [[ -z "$INPUT_ARGS" ]]; then
    echo "Missing file (pattern) to upload."
    exit 1
fi


#
# Sanity-check, show our arguments.
#
echo "Arguments : ${INPUT_ARGS}"
echo "POST URL: ${POST_URL}"
echo "REPO: ${REPO}"
echo "BRANCH: ${BRANCH}"
echo "RUN_ID: ${RUN_ID}"




#
# In the past we invoked a build-script to generate the artifacts
# prior to uploading.
#
# Now we no longer do so, they must exist before they are uploaded.
#
# Test for them here.
#

# Have we found any artifacts?
found=
for file in $INPUT_ARGS; do
    if [ -e "$file" ]; then
        found=1
    fi
done

#
# Abort if no matching files were found.
#
if [ -z "${found}" ]; then

    echo "*****************************************************************"
    echo " "
    echo " Artifacts are missing, and this action no longer invokes the "
    echo " legacy-build script."
    echo " "
    echo " Please see the README.md file for github-action-publish-binaries"
    echo " which demonstrates how to build AND upload artifacts."
    echo " "
    echo "*****************************************************************"

    exit 1
fi


#
# For each matching file..
#
for file in $INPUT_ARGS; do

    echo "Processing file ${file}"

    if [ ! -e "$file" ]; then
        echo "***************************"
        echo " file not found - skipping."
        echo "***************************"
        continue
    fi

    if [ ! -s "$file" ]; then
        echo "**************************"
        echo " file is empty - skipping."
        echo "**************************"
        continue
    fi


    FILENAME=$(basename "${file}")

    UPLOAD_URL="${POST_URL}/upload?name=${FILENAME}"
    echo "Upload URL is ${UPLOAD_URL}"

    # Generate a temporary file.
    tmp=$(mktemp)

    # Upload the artifact - capturing HTTP response-code in our output file.
    response=$(
        curl -F "ziprepo=@${file}"\
        -sSL \
        --write-out "%{http_code}" \
        --output $tmp \
        "${UPLOAD_URL}")
    echo $response
    echo "curl -F \"ziprepo=@${file}\" \"${UPLOAD_URL}\""

    # If the curl-command returned a non-zero response we must abort
    if [ "$?" -ne 0 ]; then
        echo "**********************************"
        echo " curl command did not return zero."
        echo " Aborting"
        echo "**********************************"
        cat $tmp
        rm $tmp
        exit 1
    fi

    # If upload is not successful, we must abort
    if [ $response -ge 400 ]; then
        echo "***************************"
        echo " upload was not successful."
        echo " Aborting"
        echo " HTTP status is $response"
        echo "**********************************"
        cat $tmp
        rm $tmp
        exit 1
    fi

    # Show pretty output, since we already have jq
    cat $tmp | jq .
    rm $tmp

done
